
package me.xxsniperzzxxsd.infoboard.Util;

import java.io.BufferedWriter;
import java.io.File;
import java.io.FileOutputStream;
import java.io.FileWriter;
import java.io.IOException;

import org.bukkit.Bukkit;


@SuppressWarnings("unused")
public class config {
//
//	private File configFile;
//
//	public void createConfig() {
//		configFile = new File(
//				Bukkit.getPluginManager().getPlugin("Info Board").getDataFolder(),
//				"config.yml");
//
//		try
//		{
//			FileOutputStream fos = new FileOutputStream(configFile);
//			fos.flush();
//			fos.close();
//		} catch (IOException e)
//		{
//			// TODO Auto-generated catch block
//			e.printStackTrace();
//		}
//
//		try
//		{
//			BufferedWriter bw = new BufferedWriter(new FileWriter(configFile));
//			bw.write("# Max rows is 15, and most characters in a row is 16(Unless you enable scroll) (This includes color/formating codes)");
//			bw.newLine();
//			bw.write("# The group setting will always go to default if the players group isn't found.(Scoreboards per group requires vault to be on the server)");
//			bw.newLine();
//			bw.write("# The world setting will always go to global if the players world isn't found.");
//			bw.newLine();
//			bw.newLine();
//			bw.write("# =============================================================");
//			bw.newLine();
//			bw.write("#                   Example");
//			bw.newLine();
//			bw.write("# Info Board:");
//			bw.newLine();
//			bw.write("# # Page Number");
//			bw.newLine();
//			bw.write("#   '1':");
//			bw.newLine();
//			bw.write("# # How Long this page is shown for");
//			bw.newLine();
//			bw.write("#     Show Time: 10");
//			bw.newLine();
//			bw.write("# # What world sees this page (global = All)");
//			bw.newLine();
//			bw.write("#     global:");
//			bw.newLine();
//			bw.write("# # What Permissions group sees this page");
//			bw.newLine();
//			bw.write("#       default:");
//			bw.newLine();
//			bw.write("# # Pages Title");
//			bw.newLine();
//			bw.write("#         Title: '&4&lDuskHaven'");
//			bw.newLine();
//			bw.write("# # Pages Rows");
//			bw.newLine();
//			bw.write("#          Rows:");
//			bw.newLine();
//			bw.write("#          - ' '");
//			bw.newLine();
//			bw.write("#          - 'This board is only'");
//			bw.newLine();
//			bw.write("#          - 'seen by defaults'");
//			bw.newLine();
//			bw.write("#       Admin:");
//			bw.newLine();
//			bw.write("#         Title: '&4&lAdmin Page'");
//			bw.newLine();
//			bw.write("#         Rows:");
//			bw.newLine();
//			bw.write("#         - ' '");
//			bw.newLine();
//			bw.write("#         - 'This board is only'");
//			bw.newLine();
//			bw.write("#        - 'seen by Admins'");
//			bw.newLine();
//			bw.write("#  '2':");
//			bw.newLine();
//			bw.write("#    Show Time: 5");
//			bw.newLine();
//			bw.write("#    world:");
//			bw.newLine();
//			bw.write("#      default:");
//			bw.newLine();
//			bw.write("#        Title: '&a&lStats'");
//			bw.newLine();
//			bw.write("#         Rows:");
//			bw.newLine();
//			bw.write("# #              Splitting a line can be done in two ways: using <split>");
//			bw.newLine();
//			bw.write("#         - 'Online Players: <split> <onlineplayers>'");
//			bw.newLine();
//			bw.write("# #               Or Using ;");
//			bw.newLine();
//			bw.write("#         - 'Money: ; <balance>'");
//			bw.newLine();
//			bw.write("#         - 'PowerLevel: <split> <mcmmopowerlevel>'");
//			bw.newLine();
//			bw.write("#         - 'Your Level: <split> <level>'");
//			bw.newLine();
//			bw.write("#    world_the_nether:");
//			bw.newLine();
//			bw.write("#      default:");
//			bw.newLine();
//			bw.write("#        Title: '&a&lNether'");
//			bw.newLine();
//			bw.write("#         Rows:");
//			bw.newLine();
//			bw.write("#         - 'Your Level: <split> <level>'");
//			bw.newLine();
//			bw.write("# # Will only display if <exp> isn't \"0\" or \"Unkown\"");
//			bw.newLine();
//			bw.write("#         - '~!<exp>Your Exp:'");
//			bw.newLine();
//			bw.write("#         - '~!<exp><exp>'");
//			bw.newLine();
//			bw.newLine();
//			bw.write("#==================================================================");
//			bw.newLine();
//			bw.write("#Custom Variables are pretty simple, just follow this setup:");
//			bw.newLine();
//			bw.write("#Custom Variables: ");
//			bw.newLine();
//			bw.write("# Variable: What it gets replaced to");
//			bw.newLine();
//			bw.write("#but when you go to use them put <Variable>");
//			bw.newLine();
//			bw.write("#==================================================================");
//			bw.newLine();
//			bw.write("Custom Variables:");
//			bw.newLine();
//			bw.write("  website: Dusk-Haven.com");
//			bw.newLine();
//			bw.write("  plugindev: SniperzCiinema");
//			bw.newLine();
//			bw.newLine();
//			bw.write("#==================================================================");
//			bw.newLine();
//			bw.write("#Any worlds you want disabled put them here!  ");
//			bw.newLine();
//			bw.write("#==================================================================");
//			bw.newLine();
//			bw.write("Disabled Worlds:");
//			bw.newLine();
//			bw.write("- DisabledWorld1");
//			bw.newLine();
//			bw.write("- DisabledWorld2");
//			bw.newLine();
//			bw.newLine();
//			bw.write("#==================================================================");
//			bw.newLine();
//			bw.write("#Just a heads up, using scroll MAY cause some lag. That's why it's a config option");
//			bw.newLine();
//			bw.write("#<scroll> remove the limit of characters in a row as it scrolls through");
//			bw.newLine();
//			bw.write("#To enable this turn, change \"Scrolling Text.Enable\" to true, and restart the server");
//			bw.newLine();
//			bw.write("#Shift Time is how long between letters move");
//			bw.newLine();
//			bw.write("#==================================================================");
//			bw.newLine();
//			bw.write("Scrolling Text:");
//			bw.newLine();
//			bw.write("  Enable: false");
//			bw.newLine();
//			bw.write("  Shift Time: 1");
//			bw.newLine();
//			bw.newLine();
//			bw.write("#==================================================================");
//			bw.newLine();
//			bw.write("#How many seconds between updating the scoreboard");
//			bw.newLine();
//			bw.write("#==================================================================");
//			bw.newLine();
//			bw.write("Update Time: 2");
//			bw.newLine();
//			bw.newLine();
//			bw.write("#==================    SCORE BOARDS      ======================");
//			bw.newLine();
//			bw.write("#Max rows is 15, and most characters in a row is 16(Unless you enable scroll) (This includes color/formating codes)");
//			bw.newLine();
//			bw.write("#The group setting will always go to default if the players group isn't found.(Scoreboards per group requires vault to be on the server)");
//			bw.newLine();
//			bw.write("#The world setting will always go to global if the players world isn't found.");
//			bw.newLine();
//			bw.write("#==================================================================");
//			bw.newLine();
//			bw.newLine();
//			bw.write("Info Board:");
//			bw.newLine();
//			bw.write("  '1':");
//			bw.newLine();
//			bw.write("    Show Time: 10");
//			bw.newLine();
//			bw.write("    global:");
//			bw.newLine();
//			bw.write("      default:");
//			bw.newLine();
//			bw.write("        Title: '&e<plugindev>'");
//			bw.newLine();
//			bw.write("        Rows:");
//			bw.newLine();
//			bw.write("        - ' '");
//			bw.newLine();
//			bw.write("        - '&e&lWelcome! ; 99'");
//			bw.newLine();
//			bw.write("        - '&l<player> ; 99'");
//			bw.newLine();
//			bw.write("        - ' '");
//			bw.newLine();
//			bw.write("        - '&e&lServer TPS:'");
//			bw.newLine();
//			bw.write("        - '&7<tps>'");
//			bw.newLine();
//			bw.write("        - ' '");
//			bw.newLine();
//			bw.write("       - '&aSetting up '");
//			bw.newLine();
//			bw.write("       - '&bInfoBoard is'");
//			bw.newLine();
//			bw.write("       - '&cpretty simple.'");
//			bw.newLine();
//			bw.write("       - '&dJust edit the'");
//			bw.newLine();
//			bw.write("       - '&econfig!'");
//			bw.newLine();
//			bw.write("  '2':");
//			bw.newLine();
//			bw.write("    Show Time: 10");
//			bw.newLine();
//			bw.write("    global:");
//			bw.newLine();
//			bw.write("      default:");
//			bw.newLine();
//			bw.write("        Title: '&4&nExample:'");
//			bw.newLine();
//			bw.write("        Rows:");
//			bw.newLine();
//			bw.write("        - '&6<nuke>----~<skull>~----<nuke>'");
//			bw.newLine();
//			bw.write("        - ' '");
//			bw.newLine();
//			bw.write("        - '&e&lWelcome!'");
//			bw.newLine();
//			bw.write("        - '&l<player>'");
//			bw.newLine();
//			bw.write("        - ' '");
//			bw.newLine();
//			bw.write("        - '&a&lOnline:'");
//			bw.newLine();
//			bw.write("        - <onlineplayers>");
//			bw.newLine();
//			bw.write("        - ' '");
//			bw.newLine();
//			bw.write("        - '~!<level>&6&lLevel:'");
//			bw.newLine();
//			bw.write("        - '~!<level>&e<level>'");
//			bw.newLine();
//			bw.write("        - ' '");
//			bw.newLine();
//			bw.write("        - '&e&lWebsite:'");
//			bw.newLine();
//			bw.write("        - <website>");
//			bw.newLine();
//			bw.write("        - '&6<nuke>----=<skull>=----<nuke>'");
//			bw.newLine();
//			bw.write("  '3':");
//			bw.newLine();
//			bw.write("    Show Time: 10");
//			bw.newLine();
//			bw.write("    global:");
//			bw.newLine();
//			bw.write("      default:");
//			bw.newLine();
//			bw.write("        Title: '&4&nExample 2:'");
//			bw.newLine();
//			bw.write("        Rows:");
//			bw.newLine();
//			bw.write("        - '&6<nuke>----~<skull>~----<nuke>'");
//			bw.newLine();
//			bw.write("        - ' '");
//			bw.newLine();
//			bw.write("        - '&e&lWelcome!'");
//			bw.newLine();
//			bw.write("        - '&l<player>'");
//			bw.newLine();
//			bw.write("        - ' '");
//			bw.newLine();
//			bw.write("        - '&a&lOnline:'");
//			bw.newLine();
//			bw.write("        - <onlineplayers>");
//			bw.newLine();
//			bw.write("        - ' '");
//			bw.newLine();
//			bw.write("        - '~!<level>&6&lLevel:'");
//			bw.newLine();
//			bw.write("        - '~!<level>&e<level>'");
//			bw.newLine();
//			bw.write("        - ' '");
//			bw.newLine();
//			bw.write("        - '&e&lWebsite:'");
//			bw.newLine();
//			bw.write("        - <website>");
//			bw.newLine();
//			bw.write("        - '&6<nuke>----=<skull>=----<nuke>'");
//		} catch (IOException ioe)
//		{
//			// file saving failed
//		}
//
//	}
}
