name: Info-Board
main: me.xxsniperzzxxsd.infoboard.InfoBoard
version: 0.2.3C
author: SniperzCiinema
description: Show an info board
softdepend: [AncientRPG, Cranked, Essentials, Factions, Heroes, Infected, Jobs, LWC, mcMMO, McTowns, MiniGames, Multiverse-Core, PlayerPoints, PlotMe, PrisonRankup, PVPArena, SimpleClans, Stats, Towny, WorldGuard, AncientRPG]

commands:
    InfoBoard:
        usage: /<command>
        description: The main command for this plugin
        aliases: [ib, iboard, infob]
        
permissions:
    InfoBoard.*:
        default: op
        children:
            InfoBoard.Set: true
            InfoBoard.Toggle: true
            InfoBoard.Reload: true
            InfoBoard.View: true
    InfoBoard.View:
        default: true